apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-config
data:
  app.properties: |-
    appName={{ .Values.config.appName }}
    appDescription={{ .Values.config.appDescription }}
    appAuthor={{ .Values.config.appAuthor }}
    appVersion={{ .Values.config.appVersion }}
    message={{ .Values.config.message }}

